### ISSUE TITLE
Unable to compile "error: no such subcommand: build-bpf"

### ISSUE THREAD

**Issue by siulynot** [Bonfida/bonfida-bot#4]
When i try to compile with "make" i get this: 

```
cargo build-bpf --manifest-path "third_party/serum_dex/dex/Cargo.toml" --bpf-out-dir target/deploy
error: no such subcommand: `build-bpf`
make: *** [Makefile:8: serum_dex.so] Error 101
root@3ba2e7f1e1fa:/bonfida-bot/program# /bin/sh: 1: cargo: not found
bash: /bin/sh:: No such file or directory
```

I assume it requires this package: https://crates.io/crates/solana-cargo-build-bpf/1.4.9 

The crates.io site says the package has been yanked.

When i try : ` cargo install solana-cargo-build-bp     `                                                                                                                                                 
  i get: 
```
  Updating crates.io index error: could not find `solana-cargo-build-bp` in registry `https://github.com/rust-lang/crates.io-index` with version `*` 
```
Please some help would be appreciated, thanks.

**Comment by Lcchy** [comment]
Hi @siulynot, I think you're missing a dependency indeed, try to install the solana toolsuite from here:
https://docs.solana.com/cli/install-solana-cli-tools

We should maybe put this in the readme

**Comment by siulynot** [comment]
great!. Got it working, thanks! I needed the solana tool suite.
