### ISSUE TITLE
Bot Pool Creation: Error creating the pool Error: Timed out awaiting confirmation on transaction

### ISSUE THREAD

**Issue by HankHoneymoon** [Bonfida/bonfida-bot#5]
Setting up a pool for Raydium USDC has returned errors upon creating the pool, using both Solana SPL Token Wallet and Mathwallet. 

Troubleshooting efforts:
Using both/either wallet,
Unlocking wallet and approving all transactions from the sit
Repeating after waiting some time. 

Thanks for any help.

Mathwallet error: "Error creating the pool TypeError: Failed to fetch"
Solana SPL error: "Bot Pool Creation: Error creating the pool Error: Timed out awaiting confirmation on transaction"

Most recent sig:
4DAomwgLyHSy1mUNvQMAqKTxuQPpVJTafqirggQb1DbPFxBcN39MMd9k51ZDVxviUUPkj6PayX6tw9F6AneGpsyi

**Comment by HankHoneymoon** [comment]
I've got funds in wallet, verified on Bonfida balances page as well.

**Comment by dr497** [comment]
This is an error due to Solana RPC nodes

**Comment by HankHoneymoon** [comment]
Seems like some time was all that was needed. Bot is up testing with minimal funds, just to be safe. Cheers.
